/*
 * bitmapDIBHeader.h
 *
 *  Created on: Nov 7, 2020
 *      Author: blazer
 */

#ifndef SRC_BMP_BITMAPDIBHEADER_H_
#define SRC_BMP_BITMAPDIBHEADER_H_

enum HEADER_SIZE
{
	BITMAPCOREHEADER = 12,
	OS22XBITMAPHEADER = 16,
	BITMAPCOREHEADER2 = 64,
	BITMAPINFOHEADER = 40,
	BITMAPV2INFOHEADER = 52,
	BITMAPV3INFOHEADER = 56,
	BITMAPV4HEADER = 108,
	BITMAPV5HEADER = 124
};

enum COMPRESSION_TYPE
{
	BI_RGB = 0,
	BI_RLE8 = 1,
	BI_RLE4 = 2,
	BI_BITFIELDS = 3,
	BI_JPEG = 4,
	BI_PNG = 5,
	BI_ALPHABITFIELDS = 6,
	BI_CMYK = 11,
	BI_CMYKRLE8 = 12,
	BI_CMYKRLE4 = 13
};

class bitmapDIBHeader {
public:
	HEADER_SIZE size;
	bitmapDIBHeader(HEADER_SIZE size = BITMAPV5HEADER);
	virtual ~bitmapDIBHeader();
	unsigned char * getByteArray();
};

#endif /* SRC_BMP_BITMAPDIBHEADER_H_ */
